Use Iterable from collections.abc
Iterable was removed from the collections module in python ~3.8. It has
been in collections.abc since python 3.3.

fixes:
    File "/home/clayton/src/valve-infra/venv/lib/python3.10/site-packages/vulkan/_vulkan.py", line 74, in _cast_ptr2
      if isinstance(x, _collections.Iterable):
  AttributeError: module 'collections' has no attribute 'Iterable'